name: raya_ai
description: "Raya AI - Yapay zeka destekli cilt analizi ve kişiselleştirilmiş cilt bakım önerileri sunan mobil uygulama."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.2.1

  # Backend & Database
  supabase_flutter: ^2.10.3

  # Local Storage
  shared_preferences: ^2.5.3

  # Media
  image_picker: ^1.2.0

  # UI Components
  table_calendar: ^3.1.2
  fl_chart: ^1.1.0

  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0

dependency_overrides:
  vector_math: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
